from enum import Enum


class VerificationStatus(str, Enum):
    VERIFIED = "VERIFIED"
    PROBABLE = "PROBABLE"
    UNVERIFIED = "UNVERIFIED"
    NOT_FOUND = "NOT_FOUND"
    CONFLICTING_DATA = "CONFLICTING_DATA"


class OrganizationRole(str, Enum):
    ORIGINAL_BUILDER = "ORIGINAL_BUILDER"
    EPC_CONTRACTOR = "EPC_CONTRACTOR"
    CURRENT_MAINTAINER = "CURRENT_MAINTAINER"
    REHABILITATION_CONTRACTOR = "REHABILITATION_CONTRACTOR"
    INSPECTION_AGENCY = "INSPECTION_AGENCY"
    CONSULTANT = "CONSULTANT"
    OWNER = "OWNER"
    AUTHORITY = "AUTHORITY"


class SourceDeclarationType(str, Enum):
    LIVE_API = "LIVE_API"
    DOWNLOAD_DATASET = "DOWNLOAD_DATASET"
    GIS_SERVICE = "GIS_SERVICE"
    PUBLIC_PORTAL = "PUBLIC_PORTAL"
    DOCUMENT = "DOCUMENT"
    UNKNOWN = "UNKNOWN"


class InfrastructureTypeHint(str, Enum):
    ROAD = "ROAD"
    BRIDGE = "BRIDGE"
    FLYOVER = "FLYOVER"
    TUNNEL = "TUNNEL"
    BUILDING = "BUILDING"
    DAM = "DAM"
    OTHER = "OTHER"
