# configs/model.yaml
model:
  name: "yolo11m" # Options: yolo11n, yolo11s, yolo11m, yolo11l, yolo11x
  pretrained: true
  checkpoint_path: null # Path to load custom weights (e.g. for resuming)
  image_size: 640
  channels: 3
  
  # Structural options
  backbone: "default"
  head: "default"
